# Generated by Django 5.0.6 on 2024-07-28 11:24

import django.db.models.deletion
import network_scanner.utils.validators.ip_validator
import network_scanner.utils.validators.number_range_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_session_name', models.CharField(max_length=50, verbose_name='Name of this scan')),
                ('base_ip_address', models.CharField(max_length=15, validators=[network_scanner.utils.validators.ip_validator.IPValidator], verbose_name='IP address')),
                ('ip_range', models.PositiveIntegerField(validators=[network_scanner.utils.validators.number_range_validator.PortRangeNumberRangeValidator], verbose_name='IP range')),
                ('random_or_not', models.CharField(choices=[('r', 'Random'), ('nr', 'Not Random')], max_length=2, verbose_name='IP generation method')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkScanningSessionIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, validators=[network_scanner.utils.validators.ip_validator.IPValidator], verbose_name='IP address')),
                ('is_up', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('ns', 'Not Scanned')], max_length=4, verbose_name='Server status')),
                ('related_scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_scanner.networkscanningsession', verbose_name='Related scan session')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=15, validators=[network_scanner.utils.validators.number_range_validator.IPRangeNumberRangeValidator], verbose_name='IP address')),
                ('is_open', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('ns', 'Not Scanned')], max_length=4, verbose_name='port status')),
                ('related_ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_scanner.networkscanningsessionipaddress', verbose_name='Related scan session')),
            ],
        ),
    ]
