# Generated by Django 5.0.6 on 2024-07-28 12:13

import network_scanner.utils.validators.ip_validator
import network_scanner.utils.validators.number_range_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscanningsession',
            name='base_ip_address',
            field=models.CharField(max_length=15, validators=[network_scanner.utils.validators.ip_validator.ip_validator], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='networkscanningsession',
            name='ip_range',
            field=models.PositiveIntegerField(validators=[network_scanner.utils.validators.number_range_validator.ip_range_number_range_validator], verbose_name='IP range'),
        ),
        migrations.AlterField(
            model_name='networkscanningsessionipaddress',
            name='ip_address',
            field=models.CharField(max_length=15, validators=[network_scanner.utils.validators.ip_validator.ip_validator], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='openport',
            name='port',
            field=models.CharField(max_length=15, validators=[network_scanner.utils.validators.number_range_validator.port_range_number_range_validator], verbose_name='Port Number'),
        ),
    ]
