# Generated by Django 5.0.6 on 2024-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scanner', '0002_alter_networkscanningsession_base_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscanningsessionipaddress',
            name='is_up',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('ns', 'Not Scanned'), ('ic', 'Incorrect IP Address')], max_length=4, verbose_name='Server status'),
        ),
        migrations.AlterField(
            model_name='openport',
            name='is_open',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('ns', 'Not Scanned')], max_length=5, verbose_name='port status'),
        ),
    ]
